### ISSUE TITLE
fail to captureRoboImage due to `could not find any node`

### ISSUE THREAD

**Issue by mengdd** [takahirom/roborazzi-usage-examples#7]
Hello, when I clone this repo and trying to run in locally:

```
./gradlew app:recordRoborazziDebug
```

the `FirstRobolectricComposeTest` `roborazziTest` is always failing with below error:
```
java.lang.AssertionError: fail to captureRoboImage
Reason: Expected exactly '1' node but could not find any node that satisfies: (Text + EditableText contains 'Hello Robolectric!' (ignoreCase: false))

	at androidx.compose.ui.test.SemanticsNodeInteraction.fetchOneOrDie(SemanticsNodeInteraction.kt:145)
	at androidx.compose.ui.test.SemanticsNodeInteraction.fetchSemanticsNode(SemanticsNodeInteraction.kt:79)
	at com.github.takahirom.roborazzi.RoborazziKt.captureRoboImage(Roborazzi.kt:220)
	at com.github.takahirom.roborazzi.RoborazziKt.captureRoboImage(Roborazzi.kt:210)
	at com.github.takahirom.roborazzi.RoborazziKt.captureRoboImage$default(Roborazzi.kt:205)
	at com.github.takahirom.roborazzi.usage.examples.FirstRobolectricComposeTest.roborazziTest(FirstRobolectricComposeTest.kt:39)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
```

anything went wrong?

**Comment by takahirom** [comment]
Thanks! We might have to use `Hello Roborazzi!` instead.
https://github.com/takahirom/roborazzi-usage-examples/blob/30c640f2abca224260c260c9599c33f971db83f1/app/src/test/java/com/github/takahirom/roborazzi/usage/examples/FirstRobolectricComposeTest.kt#L34-L38

**Comment by mengdd** [comment]
Please fix the typo and feel free to close this issue when it's fixed.
